// <auto-generated />
using System;
using DentalCollegeManagementSystem_AAU.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DentalCollegeManagementSystem_AAU.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.AllocatedStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("PatientID", "AppUserId")
                        .IsUnique();

                    b.ToTable("AllocatedStudents");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentID"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentDay")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ClinicID")
                        .HasColumnType("int");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeFrom")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TimeTo")
                        .HasColumnType("time");

                    b.HasKey("AppointmentID");

                    b.HasIndex("ClinicID");

                    b.HasIndex("PatientID");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Clinic", b =>
                {
                    b.Property<int>("ClinicID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClinicID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClinicID");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Competency", b =>
                {
                    b.Property<int>("CompetencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetencyID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("int");

                    b.Property<int?>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("CompetencyID");

                    b.HasIndex("PatientID");

                    b.ToTable("Competency");

                    b.HasData(
                        new
                        {
                            CompetencyID = 1,
                            CategoryName = "Clinical Examination",
                            CategoryOrder = 1,
                            IsCompleted = false,
                            ItemName = "Medical History Assessment",
                            ItemOrder = 1
                        },
                        new
                        {
                            CompetencyID = 2,
                            CategoryName = "Clinical Examination",
                            CategoryOrder = 1,
                            IsCompleted = false,
                            ItemName = "Extraoral Examination",
                            ItemOrder = 2
                        },
                        new
                        {
                            CompetencyID = 3,
                            CategoryName = "Clinical Examination",
                            CategoryOrder = 1,
                            IsCompleted = false,
                            ItemName = "Intraoral Examination",
                            ItemOrder = 3
                        },
                        new
                        {
                            CompetencyID = 4,
                            CategoryName = "Clinical Examination",
                            CategoryOrder = 1,
                            IsCompleted = false,
                            ItemName = "Periodontal Assessment",
                            ItemOrder = 4
                        },
                        new
                        {
                            CompetencyID = 5,
                            CategoryName = "Diagnostic Procedures",
                            CategoryOrder = 2,
                            IsCompleted = false,
                            ItemName = "Radiographic Interpretation",
                            ItemOrder = 1
                        },
                        new
                        {
                            CompetencyID = 6,
                            CategoryName = "Diagnostic Procedures",
                            CategoryOrder = 2,
                            IsCompleted = false,
                            ItemName = "Treatment Planning",
                            ItemOrder = 2
                        },
                        new
                        {
                            CompetencyID = 7,
                            CategoryName = "Diagnostic Procedures",
                            CategoryOrder = 2,
                            IsCompleted = false,
                            ItemName = "Case Presentation",
                            ItemOrder = 3
                        },
                        new
                        {
                            CompetencyID = 8,
                            CategoryName = "Restorative Dentistry",
                            CategoryOrder = 3,
                            IsCompleted = false,
                            ItemName = "Cavity Preparation",
                            ItemOrder = 1
                        },
                        new
                        {
                            CompetencyID = 9,
                            CategoryName = "Restorative Dentistry",
                            CategoryOrder = 3,
                            IsCompleted = false,
                            ItemName = "Direct Restoration Placement",
                            ItemOrder = 2
                        },
                        new
                        {
                            CompetencyID = 10,
                            CategoryName = "Restorative Dentistry",
                            CategoryOrder = 3,
                            IsCompleted = false,
                            ItemName = "Finishing and Polishing",
                            ItemOrder = 3
                        },
                        new
                        {
                            CompetencyID = 11,
                            CategoryName = "Periodontics",
                            CategoryOrder = 4,
                            IsCompleted = false,
                            ItemName = "Scaling and Root Planing",
                            ItemOrder = 1
                        },
                        new
                        {
                            CompetencyID = 12,
                            CategoryName = "Periodontics",
                            CategoryOrder = 4,
                            IsCompleted = false,
                            ItemName = "Oral Hygiene Instructions",
                            ItemOrder = 2
                        },
                        new
                        {
                            CompetencyID = 13,
                            CategoryName = "Professional Skills",
                            CategoryOrder = 5,
                            IsCompleted = false,
                            ItemName = "Patient Communication",
                            ItemOrder = 1
                        },
                        new
                        {
                            CompetencyID = 14,
                            CategoryName = "Professional Skills",
                            CategoryOrder = 5,
                            IsCompleted = false,
                            ItemName = "Infection Control",
                            ItemOrder = 2
                        },
                        new
                        {
                            CompetencyID = 15,
                            CategoryName = "Professional Skills",
                            CategoryOrder = 5,
                            IsCompleted = false,
                            ItemName = "Documentation",
                            ItemOrder = 3
                        },
                        new
                        {
                            CompetencyID = 16,
                            CategoryName = "Professional Skills",
                            CategoryOrder = 5,
                            IsCompleted = false,
                            ItemName = "Time Management",
                            ItemOrder = 4
                        });
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Condition", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConditionID"));

                    b.Property<string>("ConditionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrentlyActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int?>("YearOfDiagnosis")
                        .HasColumnType("int");

                    b.HasKey("ConditionID");

                    b.HasIndex("PatientID");

                    b.ToTable("Conditions");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ConsentOrder", b =>
                {
                    b.Property<int>("ConsentOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsentOrderID"));

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ConsentOrderID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("ConsentOrder");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DentalChartSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BpeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReportJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionNote")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("DentalChartSessions");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DentalHistory", b =>
                {
                    b.Property<int>("DentalHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DentalHistoryID"));

                    b.Property<bool?>("AttendedAppointment")
                        .HasColumnType("bit");

                    b.Property<string>("BrushingFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrushingTechnique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DentalFloss")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FirstAppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrequencyOfDentalCheckup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InterdentalBrushes")
                        .HasColumnType("bit");

                    b.Property<bool>("Mouthwash")
                        .HasColumnType("bit");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<bool>("TongueCleaner")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfToothbrush")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfToothpaste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WaterFlosser")
                        .HasColumnType("bit");

                    b.HasKey("DentalHistoryID");

                    b.HasIndex("PatientID");

                    b.ToTable("DentalHistories");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DentalToothData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiseaseToolId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InsideToolId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OthersToolId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PreviousToolId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("ToothId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ToothId", "AreaName")
                        .IsUnique();

                    b.ToTable("DentalToothData");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DischargeOrder", b =>
                {
                    b.Property<int>("DischargeOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DischargeOrderID"));

                    b.Property<string>("AfterCareInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DischargeReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUpPlan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("DischargeOrderID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("DischargeOrder");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ExtraoralExam", b =>
                {
                    b.Property<int>("ExtraoralExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraoralExamID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacialProfile")
                        .HasColumnType("int");

                    b.Property<int>("FacialSymmetry")
                        .HasColumnType("int");

                    b.Property<string>("LymphNodesPalpation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PhotoContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkinColor")
                        .HasColumnType("int");

                    b.Property<string>("TMJExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExtraoralExamID");

                    b.HasIndex("PatientID");

                    b.ToTable("ExtraoralExams");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ExtraoralExamPhoto", b =>
                {
                    b.Property<int>("ExtraoralExamPhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtraoralExamPhotoID"));

                    b.Property<int>("ExtraoralExamID")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoSection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ExtraoralExamPhotoID");

                    b.HasIndex("ExtraoralExamID");

                    b.ToTable("ExtraoralExamPhotos");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.IntraoralExam", b =>
                {
                    b.Property<int>("IntraoralExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntraoralExamID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FloorOfMouth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OcclusionClassification")
                        .HasColumnType("int");

                    b.Property<int>("OralHygieneStatus")
                        .HasColumnType("int");

                    b.Property<string>("OralMucosa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherFindings")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Palate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PhotoContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TongueExamination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IntraoralExamID");

                    b.HasIndex("PatientID");

                    b.ToTable("IntraoralExams");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.IntraoralExamPhoto", b =>
                {
                    b.Property<int>("IntraoralExamPhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IntraoralExamPhotoID"));

                    b.Property<int>("IntraoralExamID")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoSection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IntraoralExamPhotoID");

                    b.HasIndex("IntraoralExamID");

                    b.ToTable("IntraoralExamPhotos");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalHistoryID"));

                    b.Property<bool>("Allergies")
                        .HasColumnType("bit");

                    b.Property<string>("AllergyNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CaseComplexity")
                        .HasColumnType("int");

                    b.Property<int?>("ChangesStatus")
                        .HasColumnType("int");

                    b.Property<string>("HospitalizationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBreastfeeding")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MedicalHistoryReviewedThisVisit")
                        .HasColumnType("bit");

                    b.Property<bool>("MedicalHistoryVerified")
                        .HasColumnType("bit");

                    b.Property<string>("OngoingTreatment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<bool>("RecentHospitalization")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MedicalHistoryID");

                    b.HasIndex("PatientID");

                    b.ToTable("MedicalHistories");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Medication", b =>
                {
                    b.Property<int>("MedicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlagType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("MedicationID");

                    b.HasIndex("PatientID");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.MedicationOrder", b =>
                {
                    b.Property<int>("MedicationOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicationOrderID"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("MedicationOrderID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("MedicationOrder");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<string>("AdminApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdminApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("CreatedByUserID");

                    b.HasIndex("PatientID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AttendanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FourthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NationalID_PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nationality")
                        .HasColumnType("int");

                    b.Property<string>("PatientStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfilePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientID");

                    b.HasIndex("StatusID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.PatientPhoto", b =>
                {
                    b.Property<int>("PatientPhotoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientPhotoID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PatientPhotoID");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientPhotos");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.PatientStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientID");

                    b.ToTable("PatientStatusHistories");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Radiograph", b =>
                {
                    b.Property<int>("RadiographID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RadiographID"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RadiographType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("RadiographID");

                    b.HasIndex("PatientID");

                    b.ToTable("Radiographs");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ReferralOrder", b =>
                {
                    b.Property<int>("ReferralOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferralOrderID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReferralDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferredTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReferralOrderID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("ReferralOrder");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.SocialHistory", b =>
                {
                    b.Property<int>("SocialHistoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialHistoryID"));

                    b.Property<string>("AlcoholDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlcoholFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlcoholQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlcoholType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConsumesAlcohol")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrugDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugFrequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugQuantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<int>("SmokingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsesRecreationalDrugs")
                        .HasColumnType("bit");

                    b.HasKey("SocialHistoryID");

                    b.HasIndex("PatientID");

                    b.ToTable("SocialHistories");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusID");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDescription = "Patient just registered",
                            StatusName = "Active"
                        },
                        new
                        {
                            StatusID = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDescription = "Patient accepted",
                            StatusName = "Accepted"
                        },
                        new
                        {
                            StatusID = 3,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDescription = "Appointment taken",
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusID = 4,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDescription = "Treatment started",
                            StatusName = "In Treatment"
                        },
                        new
                        {
                            StatusID = 5,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDescription = "Treatment completed",
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusID = 6,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StatusDescription = "Patient rejected",
                            StatusName = "Rejected"
                        });
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.TreatmentProcedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdminApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedSessions")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Procedure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ToothNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("TreatmentProcedures");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Visit", b =>
                {
                    b.Property<int>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitID"));

                    b.Property<string>("AdminApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AdminApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentPeriod")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Attended")
                        .HasColumnType("bit");

                    b.Property<string>("ChiefComplaint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Complications")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialsUsed")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("ProceduresPerformed")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StudentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SupervisorComments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitID");

                    b.HasIndex("PatientID");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.XRayOrder", b =>
                {
                    b.Property<int>("XRayOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("XRayOrderID"));

                    b.Property<string>("ClinicalIndication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToothNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XRayType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("XRayOrderID");

                    b.HasIndex("OrderID")
                        .IsUnique();

                    b.ToTable("XRayOrder");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.AllocatedStudent", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.AppUser", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Appointment", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Clinic", null)
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicID");

                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Competency", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Condition", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ConsentOrder", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Order", "Order")
                        .WithOne("ConsentDetail")
                        .HasForeignKey("DentalCollegeManagementSystem_AAU.Models.ConsentOrder", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DentalHistory", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DentalToothData", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.DentalChartSession", "Session")
                        .WithMany("ToothData")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DischargeOrder", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Order", "Order")
                        .WithOne("DischargeDetail")
                        .HasForeignKey("DentalCollegeManagementSystem_AAU.Models.DischargeOrder", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ExtraoralExam", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ExtraoralExamPhoto", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.ExtraoralExam", "ExtraoralExam")
                        .WithMany("Photos")
                        .HasForeignKey("ExtraoralExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtraoralExam");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.IntraoralExam", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.IntraoralExamPhoto", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.IntraoralExam", "IntraoralExam")
                        .WithMany("Photos")
                        .HasForeignKey("IntraoralExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntraoralExam");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.MedicalHistory", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Medication", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.MedicationOrder", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Order", "Order")
                        .WithOne("MedicationDetail")
                        .HasForeignKey("DentalCollegeManagementSystem_AAU.Models.MedicationOrder", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Note", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Order", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Patient", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.PatientPhoto", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.PatientStatusHistory", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Radiograph", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ReferralOrder", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Order", "Order")
                        .WithOne("ReferralDetail")
                        .HasForeignKey("DentalCollegeManagementSystem_AAU.Models.ReferralOrder", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.SocialHistory", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.TreatmentProcedure", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Visit", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.XRayOrder", b =>
                {
                    b.HasOne("DentalCollegeManagementSystem_AAU.Models.Order", "Order")
                        .WithOne("XRayDetail")
                        .HasForeignKey("DentalCollegeManagementSystem_AAU.Models.XRayOrder", "OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Clinic", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.DentalChartSession", b =>
                {
                    b.Navigation("ToothData");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.ExtraoralExam", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.IntraoralExam", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("DentalCollegeManagementSystem_AAU.Models.Order", b =>
                {
                    b.Navigation("ConsentDetail");

                    b.Navigation("DischargeDetail");

                    b.Navigation("MedicationDetail");

                    b.Navigation("ReferralDetail");

                    b.Navigation("XRayDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
